# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  RESOURCE_GROUP_NAME: Mixit2-rg


jobs:

- job: init

  pool:

    name: Azure Pipelines

  steps:

  - script: |

      az --version

      echo $(RESOURCE_GROUP_NAME)

      # az login
      # az appservice plan create --name WEB_APP_NAME --resource-group RESOURCE_GROUP_NAME --sku SKU_NAME