# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main



jobs:

- job: init

  pool:

    name: Azure Pipelines

  steps:

  - script: |

      az --version
      az appservice plan create 
      --name pipeline-test \
      --resource-group  Mixit2-rg \
      --sku B1 \
      --is-linux
      

      az webapp create \
      --name pipeline-test\
      --plan pipeline-test \
      --resource-group Mixit2-rg \
      --runtime "Python|3.7" \
      --deployment-local-git
